CREATE TABLE PRODUCTOS (
    idProducto INTEGER GENERATED BY DEFAULT AS IDENTITY  (START WITH 20002) PRIMARY KEY ,

    IdentificadorNegocio VARCHAR2(50) NOT NULL UNIQUE,

    ClaveProducto VARCHAR2(10) NOT NULL UNIQUE,

    NombreProducto VARCHAR2(200) NOT NULL,

    Precio NUMBER(10,2) NOT NULL,

    Activo NUMBER(1) DEFAULT 1 NOT NULL,

    FechaRegistro TIMESTAMP DEFAULT SYSTIMESTAMP,

    idUsuario INTEGER NOT NULL,
    FOREIGN KEY (idUsuario) REFERENCES UsuarioAuditoria(idUsuario)
);
SELECT * FROM UsuarioAuditoria
GRANT SELECT ON JJIMENEZ.productos TO JJIMENEZ;
CREATE TABLE UsuarioAuditoria(
idUsuario INTEGER GENERATED BY DEFAULT AS IDENTITY  (START WITH 10002) PRIMARY KEY ,
nombre  VARCHAR(50) NOT NULL,
correo  VARCHAR(50)NOT NULL,
contraseña  VARCHAR(250) NOT NULL,
CONSTRAINT uk_UsuarioAuditoria_correo UNIQUE (correo)
);

INSERT INTO UsuarioAuditoria(IdUsuario, nombre, correo, contraseña) VALUES(10001, 'Francisco', 'francisco55@email.com', 'Contraseña')
INSERT INTO PRODUCTOS (
    idProducto,
    IdentificadorNegocio,
    ClaveProducto,
    NombreProducto,
    Precio,
    Activo,
    idUsuario
) VALUES (
     20001,
    'NEG001',           
    'PROD001',          
    'Laptop Gamer XYZ', 
    15999.99,           
    1,                 
    10001               
);
select * from PRODUCTOS
INSERT INTO productos(1001,'PROD-20260527-153045', 'PROD9884', 'Papel', 'Papel tamaño carta', 500.99, 1, 'Francisco');
