spring.application.name=crudPrueba

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=JJimenez
spring.datasource.password=Password1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port:8081